version: 2
jobs:
  build:
    working_directory: ~/workinghours
    docker:
      - image: circleci/node:14.19-browsers
    steps:
      - checkout
      - restore_cache:
          key: workinghours-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: workinghours-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test:ci
